# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 12:12
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='code',
        ),
        migrations.RemoveField(
            model_name='post',
            name='phone',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.TextField(default='admin', verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
    ]
