# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authsite', '0002_auto_20170629_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='phone',
            field=models.TextField(null=True),
        ),
    ]
