# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-29 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authsite', '0003_auto_20170629_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='code',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='phone',
            new_name='password',
        ),
    ]
