# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-30 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authsite', '0005_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
